title: Pepesepulveda
description: Personal site and blog

collections:
  projects:
    output: true
    permalink: /proyectos/:name/

  blog:
    output: true
    sort_by: date
    permalink: /blog/:name/
    future: true


    
